FROM ubuntu:22.04

WORKDIR /data

RUN apt-get update && apt-get install -y wget unzip && rm -rf /var/lib/apt/lists/*

COPY get_data.sh /get_data.sh
RUN chmod +x /get_data.sh

ENTRYPOINT ["/bin/sh", "-c"]
CMD ["/get_data.sh"]
