# Import base image
FROM python:3.9-slim

# Set a working directory and running folders
WORKDIR /
RUN mkdir ./data

# Copy requirements.txt and model_sewer.py to the working directory
COPY requirements.txt .
COPY model_sewer.py .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run the sewer model
ENTRYPOINT ["python", "model_sewer.py"]
CMD []

# To run the container:
