# Import base image
FROM python:3.9-slim

# Set a working directory and running folders
WORKDIR /app
RUN mkdir ./data

# Copy requirements.txt and model_ffe.py to the working directory
COPY requirements.txt .
COPY model_ffe.py .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run the first-flush model
CMD ["python", "model_ffe.py"]

# To run the container: